apiVersion: v1
kind: ConfigMap
metadata:
  name: app-dummylogger-promtail-configmap
  labels:
    app: dummylogger
data:
  promtail.yaml: |
    server:
      log_level: info
      http_listen_port: 3101
      grpc_listen_port: 0
      
    clients:
      - url: http://loki-svc.monitoring.svc.cluster.local:3100/loki/api/v1/push
    
    positions:
      filename: /tmp/positions.yaml

    scrape_configs:
    - job_name: dummylogs
      static_configs:
        - targets:
            - localhost
          labels:
            job: dummy_logs
            host: localhost
            __path__: /var/log/dummylogs.log
      pipeline_stages:
        - regex:
            expression: ERROR\s*\\[Level <string> "(?P<level>\S+)"\\]
        - labels:
            level:

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummylogger
  name: dummylogger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummylogger
  template:
    metadata:
      labels:
        app: dummylogger
    spec:
      containers:
      - name: app-dummylogs-container
        image: busybox
        resources: {}
          ##limits:
          ##  cpu: 500m
          ##  memory: 100M
        imagePullPolicy: IfNotPresent            
        args:
        - /bin/sh
        - -c
        - >
          while true; do 

            echo "everything is awesome" >> /var/log/dummylogs.log
            sleep 5;
            echo "everything is awesome" >> /var/log/dummylogs.log
            sleep 5;
            echo "ERROR: the world is collapsing" >> /var/log/dummylogs.log
            sleep 10;

           done
        volumeMounts:
        - name: varlog
          mountPath: /var/log
    
      - name: app-dummylogs-promtail-sidecar
        image: docker.io/grafana/promtail:2.6.1
        resources:
          limits:
            cpu: 1000m
            memory: 500M        
        imagePullPolicy: IfNotPresent
        args:
        - -config.file=/etc/promtail/promtail.yaml
        ports:
        - containerPort: 3101
          name: http-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: app-dummylogger-promtail-configmap
          mountPath: /etc/promtail
    
      volumes:
      - name: varlog
        emptyDir: {}
      - name: app-dummylogger-promtail-configmap
        configMap:
          name: app-dummylogger-promtail-configmap