kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: loki-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: monitoring
  labels:
    app: loki-deployment
spec:
  selector:
    matchLabels:
      app: loki-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: loki-pod
    spec:
      hostname: loki
      containers:
        - name: loki-container
          image: grafana/loki:2.7.3
          args:
            - --config.file=/etc/loki/loki.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: loki-conf
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /data/loki
            - name: rules-data
              mountPath: /data/rules
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      volumes:
        - name: loki-conf
          configMap:
            name: loki-conf
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: rules-data
          configMap:
            name: loki-rules-conf