apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-rules-conf
  namespace: monitoring
data:
  loki-rules.yaml: |
      - name: error_on_dummy_logger
        rules:
          - alert: HighPercentageError
            expr: |
              sum(rate({app="dummylogger"} |= "error" [5m])) by (job)
                /
              sum(rate({app="dummylogger"}[5m])) by (job)
                > 0.05
            for: 10m
            labels:
                severity: page
            annotations:
                summary: Error in logs